### ISSUE TITLE
LETH 0.9.23 transaction display and address fetching

### ISSUE THREAD

**Issue by jdetychey** [inzhoop-co/LETH#5] opened 2016-12-19 15:49 UTC
Hi,

clicking on the bust shape lead to the friendlist address but sometimes after selecting the address it doens t show in the address field after. This issue is solved when rebooting the app.
also the transaction list is not displayed.

[http://pasteboard.co/bJo2JJtgX.png](http://pasteboard.co/bJo2JJtgX.png)

app: 0.9.23
phone: samsung s6

**Comment by hacktar** [comment] 2017-01-22 10:42
The problem is reproducible from second bust shape selection.
Refactoring for the modal friend choose is needed ...
WIP

**Comment by hacktar** [comment] 2017-04-22 16:42
fixed on new version

**Closed by hacktar** 2017-04-22 16:42 UTC
Labels: bug
